export const atmosData = [
  {
    title: "Racing and track follower",
    description:
      "We will be setting up a few Tracks in the grounds which they have to follow exactly without any deviations. The Tracks would have all the lighting. We plan to have the event in such a way that people who are interested to join for racing would need to follow the track , and the person with least time to complete the track would win the competition.",
    mode: "offline",
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: "3000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "67",
  },
  {
    title: "Call of duty: Chemical Warfare",
    description:
      "The teams will have to follow the clues to reach the checkpoints and solve the riddles given to them there.",
    mode: "online and offline",
    pocName1: "Sreya",
    pocNumber1: "9849090142",
    pocName2: null,
    pocNumber2: null,
    prize: "20000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "68",
  },
  {
    title: "Anatomy of Murder",
    description:
      "The teams will be sent a website link which will host the first round (quiz). Either Slido or some other site link. After answering the questions asked in this round, and after the organizers are done evaluating the results, the top 7-8 teams will make their way through to the second round where the main event begins. The teams will be provided with a dummy dead body to examine and clues will be set that will eventually lead the teams to either dead-ends or the correct event-sequence of the murder mystery/story.",
    mode: "online and offline",
    pocName1: "Sreya",
    pocNumber1: "9849090142",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "69",
  },
  {
    title: "Nuclear Blues",
    description:
      "There has been a leakage at a nuclear power plant, which has a river flowing from its neighborhood. The portion of the river between the leakage site and the human settlements has to be moderated using pollutant removing/controlling tools. Teams of 3 people will get to work on the pollutant removal task. Each group will be given a certain sum of virtual money to begin with and a list of pollutant removal technologies available, in an auction. Technologies like “coagulation agents” will bind with specific pollutant molecules and immobilize them; “membrane filters” will prevent molecules of a particular species from passing by for some time until the membrane gets clogged; one-time-use “neutralizing agents” will have the ability to eliminate a certain amount of specific species completely, etc. Each of these instruments willvary in price and will have a usage life.",
    mode: "online and offline",
    pocName1: "Subham Mishra",
    pocNumber1: "9987182325",
    pocName2: "Devansh Pandey",
    pocNumber2: "6263125926",
    prize: "3000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "70",
  },
  {
    title: "Under Pressure",
    description:
      "There will be two players per team. Each team competes against one other team of two\npeople, in a Discord voice channel, on a table which represents a “system of particles”. Of the\ntwo teams on a system, one will be Adders who add particles to the system and the other will be\nRemovers who remove particles from the system. Each table or voice channel will have four participants (two Adders, two\nRemovers), one moderator from ACE to coordinate the interaction with other systems, and one\nACE member to manage the Wordle games.",
    mode: "online and offline",
    pocName1: "Subham Mishra",
    pocNumber1: "9987182325",
    pocName2: "Devansh Pandey",
    pocNumber2: "6263125926",
    prize: "3000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "71",
  },
  {
    title: "Robotics Bootcamp",
    description:
      "ARC will be conducting a 2-3 day technical workshop in which the participants will be taught the basics of robotics with the help of a physical kit. By the end of the workshop, the participants would have built 5 robots from the kit. This will give the participants a better hands-on experience of working with physical electronic components.",
    mode: "online and offline",
    pocName1: "Shashank Raghav",
    pocNumber1: "7893703598",
    pocName2: "Tanay Ranjan",
    pocNumber2: "9987309538",
    prize: "none",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "72",
  },
  {
    title: "Stranded",
    description:
      "The aim of the competition would be to write the best possible code so as to negotiate a maze in the shortest possible time. The Robot which will start on the START tile and reach the FINISH tile in the shortest time will be nominated as the winner. It would be conducted in hybrid mode and actually run on a physical bot made by the club members.",
    mode: "online and offline",
    pocName1: "Sanjeev",
    pocNumber1: "6304763842",
    pocName2: "Rakshith Dasari",
    pocNumber2: "8121224411",
    prize: "7500",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "73",
  },
  {
    title: "Techtainment",
    description:
      "After a brief interview to shortlist candidates, ARC will mentor 20+ freshers ( if they come to campus) and sophomores and guide them in making some really cool and interactive projects which will be displayed during ATMOS. This will give the participants a closer experience of how projects are to be approached and dealt with and increase the technical culture on campus.",
    mode: "offline",
    pocName1: "Devesh S",
    pocNumber1: "7760898917",
    pocName2: "Aditya Anirudh",
    pocNumber2: "7975912430",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "74",
  },
  {
    title: "Sudostar",
    description:
      "This ATMOS, Axiom brings to you a newer, better and a novel version of the addictive daily puzzle of Sudoku, the SudoStar. A novel approach to the age old puzzle, Sudostar promises to be a fun filled event with one simple rule, the highest scorer takes home the bag.",
    mode: "offline",
    pocName1: "Shubhan Mittal",
    pocNumber1: "8454887830",
    pocName2: "Arko",
    pocNumber2: "8454887830",
    prize: "3000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "75",
  },
  {
    title: "Cryptography Workshop",
    description: "Cryptography Workshop",
    mode: "online and offline",
    pocName1: "Chirag Jaju",
    pocNumber1: "8788967730",
    pocName2: "Manull Popat",
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "76",
  },
  {
    title: "CodeDash",
    description:
      "CodeDash is the premier coding event of ATMOS. It is an online competitive coding contest based on algorithms and data structures, and aims to encourage participants to apply their knowledge towards problem solving.",
    mode: "online",
    pocName1: "Hriday Gajulapalli",
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: "50000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "77",
  },
  {
    title: "Capture The Flag",
    description:
      "Competition has a couple of questions (tasks) in range of categories. For example, Web, Forensic, Crypto, Binary or something else. Team can gain some points for every solved task. More points for more complicated tasks usually. The next task in chain can be opened only after some team solve previous task. Then the game time is over sum of points shows you a CTF winer.",
    mode: "online",
    pocName1: "Anshul Kanodia",
    pocNumber1: "6203070167",
    pocName2: "Chirag Jaju",
    pocNumber2: "8788967730",
    prize: "20000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "78",
  },
  {
    title: "Fastest Frontend First",
    description:
      "Participants will be given a sample frontend (one webpage). The team which replicates the wireframe in the least time and with the highest quality will be awarded. The event will be of two rounds with different difficulty levels of the designs.",
    mode: "online and offline",
    pocName1: "Shivansh",
    pocNumber1: "7069448535",
    pocName2: "Khooshrin",
    pocNumber2: "8879150554",
    prize: "20000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "79",
  },
  {
    title: "Web 3.0 workshop/talk",
    description: "Web 3.0 Workshop",
    mode: "online and offline",
    pocName1: "Madhur Saraf Jain",
    pocNumber1: "8962841328",
    pocName2: "Kushagra Verma",
    pocNumber2: "9717732802",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "80",
  },
  {
    title: "AI/ML workshop",
    description: "Machine Learning Workshop in 8 hrs sperading across 2 days",
    mode: "online and offline",
    pocName1: "Samarth Jain",
    pocNumber1: "9969710871",
    pocName2: "Anuradha Pandey",
    pocNumber2: "7045730796",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "81",
  },
  {
    title: "Courtroom",
    description:
      "Individuals will be given a corporate lawsuit and allotted a side among the plaintiff and the defendant. Two different individuals will be matched up on a case and will have to debate in a courtroom like simulation.",
    mode: "online and offline",
    pocName1: "Shubh",
    pocNumber1: "9413180403",
    pocName2: null,
    pocNumber2: null,
    prize: "20000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "82",
  },
  {
    title: "Escalade",
    description:
      "Modeling a multiplayer game with the functionalities (released during the commencement of the event). The focus of the event is on the communication network and algorithmic development of the functionalities within the specified time limit.",
    mode: "online",
    pocName1: "Rajiv DVK",
    pocNumber1: "7718859182",
    pocName2: "Shubham Singla",
    pocNumber2: "9914957477",
    prize: "3000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "83",
  },
  {
    title: "Paper presentation",
    description:
      "Professors will give their final judgment on quality and content.",
    mode: "online and offline",
    pocName1: "Animesh Rajput",
    pocNumber1: "8423434890",
    pocName2: "Teja Sai",
    pocNumber2: "8309246278",
    prize: "10000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "84",
  },
  {
    title: "3D Drug Modeling",
    description:
      "It is an Event that involves a hands on around the software that the students use frequently in terms of their regular research work.",
    mode: "online and offline",
    pocName1: "Saumitra",
    pocNumber1: "7999851671",
    pocName2: "Kanishk",
    pocNumber2: "7042897052",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "85",
  },
  {
    title: "Anatomy of Murder",
    description:
      "The first round being a quiz in which participants have to solve puzzles related to murder mystrey and forensics. From the first round the top 7-8 teams are selected to play the second round in which the participants are given a dummy-dead body to examine and from there on clues are set like a treasure hunt ultimately leading them to the lab where the participants have to use the clues gathered through out the event and perform certain reactions to reveal the entire history/story of murder.",
    mode: "online and offline",
    pocName1: "Saumitra",
    pocNumber1: "7999851671",
    pocName2: "Kanishk",
    pocNumber2: "7042897052",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "86",
  },
  {
    title: "Pharma Paper Presentation",
    description:
      "Students will have to submit a short abstract(100-150) for the paper they want to submit for presentation.Alternatively they can also apply for poster presentation. The posters and oral presentations will be judged by judges from CTPS (Current Trends In Pharmaceutical Sciences)",
    mode: "online and offline",
    pocName1: "Saumitra",
    pocNumber1: "7999851671",
    pocName2: "Kanishk",
    pocNumber2: "7042897052",
    prize: "25000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "87",
  },
  {
    title: "The Thevenin Code",
    description: "The Thevenin Code-Circuit Debugging and Making Competition",
    mode: "online and offline",
    pocName1: "Geetika Bansal",
    pocNumber1: "9781406844",
    pocName2: "Shreya Maheshwari",
    pocNumber2: "9649662593",
    prize: "24000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "88",
  },
  {
    title: "Line Follower",
    description: "Line Follower Competition",
    mode: "online and offline",
    pocName1: "Raghuram CS",
    pocNumber1: "9781406844",
    pocName2: "Aditya Kumar",
    pocNumber2: "9534210667",
    prize: "25000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "89",
  },
  {
    title: "Ansys and Solidworks Workshop and Talk",
    description: "Workshop on Soldiworks, Ansys",
    mode: "online and offline",
    pocName1: "Devansh Pandey",
    pocNumber1: "6263125926",
    pocName2: "Krutik Soni",
    pocNumber2: "9574694471",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "90",
  },
  {
    title: "Car Race and Workshop",
    description:
      "Conduct a workshop to explain the fundamentals of an electric vehicle. Build a RC car based on the fundamentals. Hold a car race at the end of the workshop.",
    mode: "online",
    pocName1: "Nitin Sureshkumar",
    pocNumber1: null,
    pocName2: "Ujjwal Raj Mohrana",
    pocNumber2: null,
    prize: "25000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "91",
  },
  {
    title: "Science Show",
    description:
      "It is a “Science Show” that is an Event where we will be demonstrating a series of experiments. Cloud Chamber / Bubble Chamber, Poisson Spot experiment, Super - Conducting Quantum Levitation on a mobius strip, Tesla Coil / Van de graafe Generator",
    mode: "offline",
    pocName1: "Nithyasree P G",
    pocNumber1: "9605375138",
    pocName2: "Tavishi Seth",
    pocNumber2: "8754434821",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "92",
  },
  {
    title: "ProdStorm",
    description:
      "Participants will be mailed a product management case study modeled around any real-life product (app/website/physical). This will be mailed 10 days before Orbe Novo. Participants will have to submit a deck 3 days before the final round. The decks will be graded and the shortlist for the final round will be published 2 days before the event.",
    mode: "online and offline",
    pocName1: "Prachet Choudha",
    pocNumber1: "9049902772",
    pocName2: null,
    pocNumber2: null,
    prize: "35000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "93",
  },
  {
    title: "Wall Street Business Challenge",
    description:
      "A case made in collaboration with the case company which would involve a business problem related to the company will be given. The teams will have 3-4 days (tentatively, depending on case difficulty) to solve the given case. The members would then have to submit their solutions (decks) for evaluation. These cases will be evaluated by professionals from the industry as well as student consultant teams from the club, each team will get personalized feedback from the professional and a score to correspond to the same.",
    mode: "online and offline",
    pocName1: "Sahej Dhingra",
    pocNumber1: "8586851812",
    pocName2: null,
    pocNumber2: null,
    prize: "35000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "94",
  },
  {
    title: "Midnight AV Quiz",
    description: "Post Inaugaration Quiz, (Audio-Visual general quiz) [ATMOS]",
    mode: "online",
    pocName1: "Abhay Jagannath",
    pocNumber1: "8790500333",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "95",
  },
  {
    title: "Sci-Tech Quiz",
    description: "A Science/Tech themed Quiz by Major Chandrakant Nair [ATMOS]",
    mode: "online",
    pocName1: "Abhay Jagannath",
    pocNumber1: "8790500333",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "96",
  },
  {
    title: "Bizzinga - A Buisness & Entrepreneurs Quiz",
    description:
      "A Buisness and Entrepreneurship based Quiz by The Quiz Club BPHC [ATMOS]",
    mode: "online",
    pocName1: "Abhay Jagannath",
    pocNumber1: "8790500333",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "97",
  },
  {
    title: "CSS Creative heads",
    description:
      "The objective of the game is to write HTML/CSS to replicate the given target image in the least code possible in the assigned time. In the target page, start coding in the editor area on the left. As you start typing, the output area in the middle will start rendering your code. When you're confident that the output matches the target image, hit the Submit button to see your score.",
    mode: "online",
    pocName1: "Sidharth Anulld",
    pocNumber1: "9585505132",
    pocName2: null,
    pocNumber2: null,
    prize: "15000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "98",
  },
  {
    title: "Deep Learning Workshop",
    description: "Deep Learning Workshop",
    mode: "online",
    pocName1: "Medini N B",
    pocNumber1: "9481331345",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "99",
  },
  {
    title: "Web Crawler",
    description:
      "The objective is that participating teams must create a tool that can crawl websites and generate reports on specific parameters and include suggestions on how to improve said parameters. This tool will be similar to Google Lighthouse.",
    mode: "online",
    pocName1: "Anish Guruvelli",
    pocNumber1: "8888003008",
    pocName2: null,
    pocNumber2: null,
    prize: "25000",
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "100",
  },
  {
    title: "Stargazing",
    description:
      "An exhilarating stargazing session with the club telescope (Celestron)",
    mode: "offline",
    pocName1: "Tarun",
    pocNumber1: "9052971001",
    pocName2: "Atharv",
    pocNumber2: "8878298504",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "101",
  },
];
