export const pearlData = [
  {
    title: "Bliss on plate",
    description: "food photography",
    mode: "online",
    pocName1: "Nithin",
    pocNumber1: "7981030376",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "1",
  },
  {
    title: "Spicy Ramen Challenge",
    description: "Eat a bowl of spicy Ramen and bear it for 5 min",
    mode: "offline",
    pocName1: "Nithin",
    pocNumber1: "7981030376",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "2",
  },
  {
    title: "HaHa Hunt",
    description:
      "Stand-up comedy competition. Participants perform for around 5-6 minutes each.",
    mode: "online and offline",
    pocName1: "Yash Jain",
    pocNumber1: "7726835366",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "3",
  },
  {
    title: "Improv Show",
    description: "Create an improv scene with inputs based on audience.",
    mode: "offline ",
    pocName1: "Yash Jain",
    pocNumber1: "7726835366",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "4",
  },
  {
    title: "Terpsichore ",
    description: "A Group dance competition event",
    mode: "online",
    pocName1: "Sushmita De",
    pocNumber1: "9163556472",
    pocName2: "Sanshrey Keshri",
    pocNumber2: "7331170345",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "5",
  },
  {
    title: "Ensemble ",
    description:
      "An event where participants dance in separate spaces, compile and edit their performances to make a single group entry",
    mode: null,
    pocName1: "Parth Gedia",
    pocNumber1: "9167707691",
    pocName2: "Ramkumar Venkat",
    pocNumber2: 8374117510.0,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "6",
  },
  {
    title: "Soul'O",
    description: "A Solo dance competition event",
    mode: "online",
    pocName1: "Gunjan Barua",
    pocNumber1: "7337095249",
    pocName2: "Jamuna Thallapalli",
    pocNumber2: 7995265841.0,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "7",
  },
  {
    title: "Groove ",
    description: "An offline solo dance off for GB",
    mode: "offline ",
    pocName1: "Moksh Papneja",
    pocNumber1: "8454896702",
    pocName2: "A'NAya' Kedia",
    pocNumber2: 7231031891.0,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "8",
  },
  {
    title: "Workshop",
    description: "Dance workshop by a prominent artist",
    mode: "online",
    pocName1: "Raima Datta",
    pocNumber1: "8374915964",
    pocName2: "Navya Mahajan",
    pocNumber2: 9467866510.0,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: true,
    id: "9",
  },
  {
    title: "Product Design/ Branding Contest",
    description:
      "Product design will involve making curated packaging designs and other mentioned deliverables for the given fictional product brief.",
    mode: "online",
    pocName1: "Anubhav",
    pocNumber1: "9958194803",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "10",
  },
  {
    title: "Isometric Design Contest",
    description:
      "The basic idea will be dealing with a hexagonal grid. The participants have to use the grid to create 3d figures, which can either be possible in real world (basic like cubes) to impossible ones (like the penrose triangle).",
    mode: "online",
    pocName1: "Geetha Charan",
    pocNumber1: "8331950608",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "11",
  },
  {
    title: "Ps Battle",
    description:
      "You are given a set of stock images and are totally free to turn it into whatever u want using photoshop. Most creative and coolest artworks would be awarded",
    mode: "online",
    pocName1: "Ysn Kiran",
    pocNumber1: "9379956789",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "12",
  },
  {
    title: "Natyam(Mono-acting)",
    description:
      "Immerse in the experience of mono acting where you have the whole liberty to create a stage for yourself. Utilise any prop to your benefit. Revel in emotions of jubilation, sadness, irritation, anger and showcase your versatility. Play one or many characters. Deliver enriching monologues. The ultimate test for an actor.",
    mode: "online and offline",
    pocName1: "A'NAt' Kumar Dasaur",
    pocNumber1: "9971422080",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "13",
  },
  {
    title: "Acting workshop",
    description: null,
    mode: "offline ",
    pocName1: "Karan Moza",
    pocNumber1: "9930426898",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: true,
    id: "14",
  },
  {
    title: "Scriptwriting workshop",
    description: null,
    mode: "offline ",
    pocName1: "Karan Moza",
    pocNumber1: "9930426898",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: true,
    id: "15",
  },
  {
    title: "On-mute(charades competition)",
    description:
      "To be able to convey thoughts and emotions to the audience without even a single word is the hallmark of a great actor. Gestures, expressions, poses and body language - challenge your mastery over them all in this thrilling competition of charades between teams. Correct guesses equal points - the team with the most points wins!",
    mode: "offline",
    pocName1: "Kushagra Verma",
    pocNumber1: "9717732802",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "16",
  },
  {
    title: "mime it out",
    description:
      "Life is a cycle, and mime is particularly suitable for showing fluidity, transformation, metamorphosis. Words can keep people apart; mime can be a bridge' between' them.” - Marcel Marceau. \nImmerse in the experience of miming, which is an art of portraying a character, mood, idea' or' narration by gestures and bodily movements.",
    mode: "online",
    pocName1: "Shamitha Obulu",
    pocNumber1: "8374550011",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "17",
  },
  {
    title: "Subverting Expectations",
    description:
      "A twist can be one of the most powerful storytelling devices at the hands of a writer. It is, however, a two edged sword: The Red Wedding was a twist just as much as Dany losing her shit. The key to a good twist is whether the plot laid g'rounds' for the unexpected to happen. Do you have what it takes to bring the unexpected to reality?\nThe participants are supposed to re-enact an iconic scene from a film, tv show or play. The only catch, subvert expectations. It’s up to their creativity and imagination to decide 'what' “the twist” is and they would require great acting chops to make the scene believable. The expected running time of the scene is 5-7mins.",
    mode: "online",
    pocName1: "Aditya Chopra",
    pocNumber1: "9007221485",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "18",
  },
  {
    title: "hasyashastra",
    description:
      "They say laughter is and will always be the best form of therapy. In times of difficulty, our problems can seem to magnify themselves to gigantic proportions, and a good laugh helps to shrink them to their true size, making them less intimidat'ing'. With Haasyashaastra, we’re looking for such therapists who can use their spontaneity, humor and acting skills to leave the other team in splits.",
    mode: "offline",
    pocName1: "Adit Danewa",
    pocNumber1: "8106940711",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "19",
  },
  {
    title: "Nostalgia: Photobooth ",
    description:
      "Come take pictures at our photobooth and participate in a fun microfiction event revolving around the memories being made. ",
    mode: "offline",
    pocName1: "Aditya Udupa",
    pocNumber1: "8978895029",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "20",
  },
  {
    title: "Shipwrecked",
    description:
      "An event where participants assume characters and present arguments as to why they deserve to stay in the game  aka the ship",
    mode: "online",
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "21",
  },
  {
    title: "Slam poetry ",
    description: "Come share your poetry and perform it. ",
    mode: "offline",
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "22",
  },
  {
    title: "The Shape of me",
    description:
      "A poetry writing event where the piece has to written in a specific shape, following the spirit of whichever shape is given as a prompt.",
    mode: "online and offline ",
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "23",
  },
  {
    title: "fraglore",
    description: "Valorant",
    mode: "online",
    pocName1: "Garvit Vyas",
    pocNumber1: "9686793032",
    pocName2: "Siddhant Jain",
    pocNumber2: 8839277867.0,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "24",
  },
  {
    title: "fraglore",
    description: "Csgo",
    mode: "online",
    pocName1: "Prajwal Nayak",
    pocNumber1: "8792838739",
    pocName2: "Rudraksh Tiwari",
    pocNumber2: 7067705957.0,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "25",
  },
  {
    title: "fraglore",
    description: "Rocket League",
    mode: "online",
    pocName1: "Teja Sai PV, ",
    pocNumber1: "8309246278",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "26",
  },
  {
    title: "fraglore",
    description: "Codm/Bgmi",
    mode: "online",
    pocName1: "Shyam N V",
    pocNumber1: "8604975791",
    pocName2: "Harsha",
    pocNumber2: 9440850268.0,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "27",
  },
  {
    title: "Glitterati",
    description:
      "A rampwalk event where participants use clothes to represent the theme of glitterati",
    mode: "online and offline",
    pocName1: "Devansh Mathukia",
    pocNumber1: "9869225827, 8169984251",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "28",
  },
  {
    title: "Alta costura",
    description:
      "A rampwalk event where participants use clothes to represent the theme of glitterati",
    mode: "online",
    pocName1: "Devansh Mathukia",
    pocNumber1: "9869225827, 8169984251",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "29",
  },
  {
    title: "Mr Ms Pearl",
    description:
      "A rampwalk event where participants use clothes to represent the theme of glitterati",
    mode: "online and offline",
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "30",
  },
  {
    title: "Alfaaz",
    description:
      "From the quest for words ranging to the discovery of meanings, the epiphanies and realisations from various stimuli - we all tend to pen down a few words just like that, create anecdotes for our own selves or even to issue polemics.\n\nPresenting to all the platform of Alfaaz at Pearl, BPHC, to recite your Hindi-Urdu poetry treasures and experience the thrill of performing your self written pieces, in a language of your own.",
    mode: "online",
    pocName1: "Rudra Raj Awasthi",
    pocNumber1: "8009954169",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "31",
  },
  {
    title: "Youth Mahasabha",
    description:
      "Ideate. Create. Debate. (For those who hold in captive their opinions on current affairs and possess an ardent desire to let them all free, we present the Youth Mahasabha, a Hindi debate event at Pearl, BPHC, an opportunity for you to voice your trove of beliefs, compelling others to break open theirs.)",
    mode: "online",
    pocName1: "Kartikay Dhall",
    pocNumber1: "9638930748",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "32",
  },
  {
    title:
      "Antakshari(this will be an offline event so no guarantee that this will be done)",
    description:
      "Knock knock!\nAre you the one who knows the lyrics to all the songs, or the one who vibes to all genres of music or the one who makes the best of playlists? Would you call yourself a music nerd?\nIf so, we've got some news! Presenting to you, Antakshari, but hatke.\nThe game we've all played but in a way we never have. \nJoin us to strike a feeling of nostalgia as we fight the new normal with melodies and lyrics.\nNo longer let the tune of a song stay stuck in your head. Sing it all out, right here.",
    mode: "offline",
    pocName1: "Riya Singh",
    pocNumber1: "8960709002",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "33",
  },
  {
    title: "Interview",
    description:
      "As it doesn't makes sense to call in famous celebrities as judges in online events we are planning to host an interview with a celebrity, the winners of alfaaz will be given a chance to perform in front of the guest",
    mode: "offline",
    pocName1: "Abhudaya Mishra",
    pocNumber1: "9953959223",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "34",
  },
  {
    title: "Kaleidoscope",
    description:
      "Catharsis Film Festival as a part of Pearl'22 proudly presents Kaleidoscope, It is one of the biggest Short Film competitions of the year. Your movie can be in any language, but it is compulsory to submit English subtitles along with the movie. ",
    mode: "online",
    pocName1: "Archis Sahu",
    pocNumber1: "7259028066",
    pocName2: null,
    pocNumber2: null,
    prize: 40000.0,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "35",
  },
  {
    title: "The Itinerary",
    description:
      "It is a Travel Film competition. Your vlog/film can be in any language, but it is advisable to submit English subtitles along with the vlog/film. \n\nThe vlog/film can be shot on any camera (Mobile or DSLR). They will be judged on the style and creativity and not on the quality of the footage.\n",
    mode: "offline/online and offline",
    pocName1: "Archis Sahu",
    pocNumber1: "7259028066",
    pocName2: null,
    pocNumber2: null,
    prize: 14000.0,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "36",
  },
  {
    title: "Football Manager",
    description:
      "An ascending-bid auction of the best footballers around the world, form the best teams possible with the funds available to you and compete with one another using FM simulations. ",
    mode: "online",
    pocName1: "Gaurav Singh",
    pocNumber1: "9148399911",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "37",
  },
  {
    title: "Interrofiction",
    description:
      "step into the shoes of a fictional character and create conversations across fandoms with other participants",
    mode: "online and offline",
    pocName1: "Vidhi Mehta",
    pocNumber1: "9967514181",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "38",
  },
  {
    title: "Retrospective",
    description: "online Photography Contest (Themes-TBA)",
    mode: "online",
    pocName1: "Khushi Khanna",
    pocNumber1: "7428468181",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "39",
  },
  {
    title: "Expressions",
    description:
      "Candid Photography Race-Capturing moments during the fest (offline event)",
    mode: "offline",
    pocName1: "Khushi Khanna",
    pocNumber1: "7428468181",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "40",
  },
  {
    title: "Midnight AV Quiz",
    description: "Post Inaugaration Quiz, (Audio-Visual general quiz) [ATMOS]",
    mode: "offline",
    pocName1: "Abhay Jagannath",
    pocNumber1: "8790500333",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "41",
  },
  {
    title: "Sci-Tech Quiz",
    description: "A Science/Tech themed Quiz by Major Chandrakant Nair [ATMOS]",
    mode: "online",
    pocName1: "Abhay Jagannath",
    pocNumber1: "8790500333",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "42",
  },
  {
    title: "Bizzinga - A Buisness & Entrepreneurs Quiz",
    description:
      "A Buisness and Entrepreneurship based Quiz by The Quiz Club BPHC [ATMOS]",
    mode: "offline",
    pocName1: "Abhay Jagannath",
    pocNumber1: "8790500333",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "43",
  },
  {
    title: "Open General Quiz ",
    description: "A General Quiz open to all ages by Major Chandrakant Nair",
    mode: "online",
    pocName1: "Vaibhav Jha",
    pocNumber1: "72178 34030",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "44",
  },
  {
    title: "Shifting Paradigms - A Cultural Quiz",
    description: "Cultural Themed Quiz by The Quiz Club BPHC",
    mode: "offline",
    pocName1: "Vaibhav Jha",
    pocNumber1: "72178 34030",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "45",
  },
  {
    title: "Rangeela, A Colourful Quiz",
    description: "A Quiz based on Colours by Jalaj Maheshwari",
    mode: "online",
    pocName1: "Vaibhav Jha",
    pocNumber1: "72178 34030",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "46",
  },
  {
    title: "Around The World In 80 Minutes",
    description:
      "Get ready for an adventure, as the Sanskrit and Foreign Language Club brings to you an event like no other. In Around the World in 80 Minutes, you get to experience an immersive RPG environment brought to life. Dropped into a foreign country, you are armed with only your wit and charm as you navigate the scene around you, interacting with characters that may help (or harm!) you along your journey. As you move from one country to the other, be prepared to be met with a burst of colour, flair and a whole host of intriguing personas, each crazier than the last.",
    mode: "offline",
    pocName1: "Ankita Behera",
    pocNumber1: "8280292201",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "47",
  },
  {
    title: "Renegade",
    description:
      "Behind mirages, smokescreens and veils of mystery, SaFL presents a brand-new, enigma of an event: Renegade. As you deal with lurking presences and conspicuous shadows, this event is sure to keep you on your toes.\nAs illusion and reality blend together, you’ll be second-guessing your own vision within no time.\nBe on guard, and remember, above all else: nothing it as it seems.",
    mode: "online",
    pocName1: "Sanshrey Keshri",
    pocNumber1: "7331170345",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "48",
  },
  {
    title: "Masterstroke",
    description: "An art competition. 2 categories. Black and White; Painting",
    mode: "online and offline/online",
    pocName1: "Nirmalya Ghosh",
    pocNumber1: "8179749977",
    pocName2: "Aayush Tiwari",
    pocNumber2: 9880523444.0,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "49",
  },
  {
    title: "Exhibition",
    description:
      "Members of the Club will showcase all their artworks in a classroom; if we are given access;",
    mode: "offline",
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "50",
  },
  {
    title: "Pictionary",
    description: "Pictionary",
    mode: "online and offline",
    pocName1: "Nirmalya Ghosh",
    pocNumber1: "8179749977",
    pocName2: "Aayush Tiwari",
    pocNumber2: 9880523444.0,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "51",
  },
  {
    title: "Cinematic Trailer Making",
    description:
      "Making a trailer based on your favourite character, movie, anime, TV Show etc.",
    mode: "online and offline",
    pocName1: "Sailesh Duddupudi",
    pocNumber1: "8124191868",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "52",
  },
  {
    title: "Product Commercial Making",
    description:
      "Shoot and edit a commercial about any product of your choosing",
    mode: "online and offline",
    pocName1: "Sailesh Duddupudi ",
    pocNumber1: "8124191868",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "53",
  },
  {
    title: "Shred Wars",
    description:
      "Guitarists compete to compose and play the best riffs over a given backing track",
    mode: "online",
    pocName1: "Varun Vaddiraju",
    pocNumber1: "8367012937",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "54",
  },
  {
    title: "A capella",
    description:
      "Participants have to choose a song of their choice and cover it in a cappella. No backing track/ karaoke is allowed. Clapping, finger snapping alongside 'humming' along/ singing harmonies is allowed. Each entry is to be around 1-2mins",
    mode: "online",
    pocName1: "Dhruv Gopal ",
    pocNumber1: "9620201692",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "55",
  },
  {
    title: "Chords From a Hat",
    description:
      "Participants will choose one theme out of a pool of predetermined themes. Each theme will be accompanied by a standard chord progression that will convey the emotion of the theme. Each contestant will have to submit an original composition of around 2 minutes length.",
    mode: "online",
    pocName1: "Shikhar Verma",
    pocNumber1: "7233001117",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "56",
  },
  {
    title: "Pardon My French",
    description:
      "Participants guess the song from lyrics run through google translate",
    mode: "online and offline",
    pocName1: "Samarpith Rout",
    pocNumber1: "8971702411",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "57",
  },
  {
    title: "Fuse It",
    description: "Participants create Indo-Western fusion mashups",
    mode: "online and offline",
    pocName1: "A'NAya' Pinapati",
    pocNumber1: "8367012937",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "58",
  },
  {
    title: "Masterclass on Music",
    description: "Prominent artist conducting masterclass",
    mode: "online",
    pocName1: "Antara Arvind",
    pocNumber1: "7358317077",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: true,
    id: "59",
  },
  {
    title: "Gandhaara (music vocal competition)",
    description: "Carnatic and Hindustani vocal competition ",
    mode: "online",
    pocName1: "Ramakrishna",
    pocNumber1: "8310670231",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "60",
  },
  {
    title: "Gandhaara (music instrumental competition)",
    description: "Carnatic and Hindustani instrumental competition  ",
    mode: "online",
    pocName1: "Ethiraja Balaji",
    pocNumber1: "9032055775",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "61",
  },
  {
    title: "Aakara (Dance competition)",
    description: "Indian classical dance competition ",
    mode: "online",
    pocName1: "Samyu Kamtam",
    pocNumber1: "8008004472",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Pearl.png?alt=media&token=43437f43-bab3-4eff-bfce-7b7db6ef40b2",
    link: "www.google.com",
    isWorkshop: false,
    id: "62",
  },
];
