export const pearlData = [
  {
    title: "Bliss on plate",
    description:
      "Like us, do you communicate through food?\nWell, we at cooking club believe that food is not just a human need, it is a language; and just like any other language its beauty is best portrayed through the art of presentation. \nFor this the cooking club brings you the opportunity to compete in the art of food photography. It is believed that the taste of any dish can be enhanced by the way it is put forth people. Spike  your creativity as things are gonna get nasty, or should I say tasty!!\nOnly thing you need to register for this event is the desire to communicate through food; there is no registration fee.\nYou will have submit a photo of the dish with platting, it can be any dish untill it is presented in an articulate manner.\nAlso a photo of your beautiful face with the tasty dish.",
    mode: "online",
    pocName1: "Nithin",
    pocNumber1: "7981030376",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "1",
  },
  {
    title: "Spicy Ramen Challenge",
    description:
      "We will be giving a bowl of spicy Ramen have to eat the whole thing and bear for 5min without drinking water or anything ",
    mode: "offline",
    pocName1: "Nithin",
    pocNumber1: "7981030376",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "2",
  },
  {
    title: "HaHa Hunt",
    description:
      "Stand-up comedy competition. Participants perform for around 5-6 minutes each.",
    mode: "online and offline",
    pocName1: "Yash Jain",
    pocNumber1: "7726835366",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "3",
  },
  {
    title: "Improv Show",
    description:
      "Fun and interactive event with no prior registration. Club would present a demonstration of how improv happens and audience would be invited then after to try it. No judges and an event just to familirize audience with different aspects of comedy.",
    mode: "offline",
    pocName1: "Yash Jain",
    pocNumber1: "7726835366",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "4",
  },
  {
    title: "Terpsichore",
    description:
      "Dance is a collaborative effort with each person playing a different role. Is your story worthy of the attention of thousands? Can your crew match the strength, sync, and flare of the best? If you and your crew are ready to vibe, groove, feel alive and set the stage ablaze together, then we give you Terpsichore, the group dance event of Orbe Novo.",
    mode: "online",
    pocName1: "Sushmita De",
    pocNumber1: "9163556472",
    pocName2: "Sanshrey Keshri",
    pocNumber2: "7331170345",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "5",
  },
  {
    title: "Ensemble",
    description:
      "An event where participants dance in separate spaces, compile and edit their performances to make a single group entry",
    mode: "online",
    pocName1: "Parth Gedia",
    pocNumber1: "9167707691",
    pocName2: "Ramkumar Venkat",
    pocNumber2: "8374117510",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "6",
  },
  {
    title: "Soul'O",
    description:
      "Do your feet unconsciously tap to the tunes of your favourite song? Does spending one day without dance seem next to impossible? Do you find yourself in a whole new place when the music starts to play? Well, here’s a sign for you to put on your dancing shoes and amp up your spirit. With our solo dance event Soul’O, let your body sway with the flow of rhythm and showcase your best moves.",
    mode: "online",
    pocName1: "Gunjan Barua",
    pocNumber1: "7337095249",
    pocName2: "Jamuna Thallapalli",
    pocNumber2: "7995265841",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "7",
  },
  {
    title: "Groove",
    description: "An offline solo dance off for GB",
    mode: "offline",
    pocName1: "Moksh Papneja",
    pocNumber1: "8454896702",
    pocName2: "Anullya Kedia",
    pocNumber2: "7231031891",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "8",
  },
  {
    title: "Workshop",
    description:
      "An online dance workshop conducted by prominent artist Imran Mir. Join us as Mr. Imran showcases to us the power of dance and learn some new moves. Get ready to feel the urban vibes!",
    mode: "online",
    pocName1: "Raima Datta",
    pocNumber1: "8374915964",
    pocName2: "Navya Mahajan",
    pocNumber2: "9467866510",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "9",
  },
  {
    title: "Product Design/ Branding Contest",
    description:
      "Product design will involve making curated packaging designs and other mentioned deliverables for the given fictional product brief.",
    mode: "online",
    pocName1: "Anubhav",
    pocNumber1: "9958194803",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "10",
  },
  {
    title: "Isometric Design Contest",
    description:
      "The basic idea will be dealing with a hexagonal grid. The participants have to use the grid to create 3d figures, which can either be possible in real world (basic like cubes) to impossible ones (like the penrose triangle).",
    mode: "online",
    pocName1: "Geetha Charan",
    pocNumber1: "8331950608",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "11",
  },
  {
    title: "Talk / Workshop",
    description:
      "Living with Creativity - My design journey of passion, inspiration, and chaos - byMohammad Owaiz",
    mode: null,
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "12",
  },
  {
    title: "Ps Battle",
    description:
      "You are given a set of stock images and are totally free to turn it into whatever u want using photoshop. Most creative and coolest artworks would be awarded",
    mode: "online",
    pocName1: "Ysn Kiran",
    pocNumber1: "9379956789",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "13",
  },
  {
    title: "Natyam(Mono-acting)",
    description:
      "Immerse in the experience of mono acting where you have the whole liberty to create a stage for yourself. Utilise any prop to your benefit. Revel in emotions of jubilation, sadness, irritation, anger and showcase your versatility. Play one or many characters. Deliver enriching monologues. The ultimate test for an actor.",
    mode: "online and offline",
    pocName1: "Anullt Kumar Dasaur",
    pocNumber1: "9971422080",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "14",
  },
  {
    title: "Acting workshop",
    description:
      "Lights. Camera. Action. You take a deep breath and there you are. On the stage with all the lights centering on you. The stage is now yours and it is just you and your character, but do you know how to convey a story? Want to learn from the best in the industry?\n\nLearn from the best in the art, Samhaara Theatre Group. One of the most popular and largest theatre groups in India specializes in teaching various aspects of theatre like production set design and acting. With over  35 Play Productions, over 70 workshops, and 5 theatre festivals, they sure have got a lot to teach. Join us on 2nd and 3rd April from 2 pm to 5 pm for an interactive learning experience.",
    mode: "offline",
    pocName1: "Karan Moza",
    pocNumber1: "9930426898",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "15",
  },
  {
    title: "Scriptwriting workshop",
    description:
      "Do you ever wonder how characters and stories come to life? How do different plotlines merge to form a climax?Do you ever wonder how characters and stories come to life? How do different plotlines merge to form a climax? \nEvery idea and tale is worth conveying. Learn the art of screenwriting from a film industry expert, Avirat parekh. An actor/ screenwriter/ producer by profession, he has 10 years of professional theatre experience in Mumbai and Delhi circuits. Discover your unique style of writing with his interactive workshop which will keep you on your toes. Learn how to use your words to convey emotions, develop characters that the audience can relate to, and much more. Join us on 1st April from 11 am to 1 pm for a unique workshop that will surely make you fall in love with the beautiful art of storytelling.",
    mode: "Online",
    pocName1: "Karan Moza",
    pocNumber1: "9930426898",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "16",
  },
  {
    title: "On-mute(charades competition)",
    description:
      "To be able to convey thoughts and emotions to the audience without even a single word is the hallmark of a great actor. Gestures, expressions, poses and body language - challenge your mastery over them all in this thrilling competition of charades between teams. Correct guesses equal points - the team with the most points wins!",
    mode: "offline",
    pocName1: "Kushagra Verma",
    pocNumber1: "9717732802",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "17",
  },
  {
    title: "mime it out",
    description:
      "Life is a cycle, and mime is particularly suitable for showing fluidity, transformation, metamorphosis. Words can keep people apart; mime can be a bridge between them.” - Marcel Marceau. \nImmerse in the experience of miming, which is an art of portraying a character, mood, idea or narration by gestures and bodily movements.",
    mode: "online",
    pocName1: "Shamitha Obulu",
    pocNumber1: "8374550011",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "18",
  },
  {
    title: "Subverting Expectations",
    description:
      "A twist can be one of the most powerful storytelling devices at the hands of a writer. It is, however, a two edged sword: The Red Wedding was a twist just as much as Dany losing her shit. The key to a good twist is whether the plot laid grounds for the unexpected to happen. Do you have what it takes to bring the unexpected to reality?\nThe participants are supposed to re-enact an iconic scene from a film, tv show or play. The only catch, subvert expectations. It’s up to their creativity and imagination to decide what “the twist” is and they would require great acting chops to make the scene believable. The expected running time of the scene is 5-7mins.",
    mode: "online",
    pocName1: "Aditya Chopra",
    pocNumber1: "9007221485",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "19",
  },
  {
    title: "hasyashastra",
    description:
      "They say laughter is and will always be the best form of therapy. In times of difficulty, our problems can seem to magnify themselves to gigantic proportions, and a good laugh helps to shrink them to their true size, making them less intimidating. With Haasyashaastra, we’re looking for such therapists who can use their spontaneity, humor and acting skills to leave the other team in splits.",
    mode: "offline",
    pocName1: "Adit Danewa",
    pocNumber1: "8106940711",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "20",
  },
  {
    title: "Nostalgia: Photobooth",
    description:
      "College is one of the most memorable, yet fast moving stages in our life. With nostalgia, take a minute to capture a memory. This is a micro fiction writing event inspired by the cultural fest, friends, and anything that you love and will never forget about BPHC(best entry receives a goodie bag). So, bring your friends, or your special someone, and capture a memory while making loads of new ones.",
    mode: "offline",
    pocName1: "Shreya Senapaty, Muskaan Kumar",
    pocNumber1: "7675057722, 9175922430",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "21",
  },
  {
    title: "Shipwrecked",
    description:
      "A host of your favorite characters from popular culture find themselves on a sinking ship. The problem - There is only one life jacket. Put yourself in their shoes and argue for why they deserve to keep their life the most.",
    mode: "offline",
    pocName1: "Ribhu Jain, Siddarth Enagala",
    pocNumber1: "8529731641, 98486 11203",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "22",
  },
  {
    title: "Retelling",
    description:
      "We all have characters we love, characters, whose stories are left untold, characters who stay a part of the protagonist. In retelling, you are the author. You have a chance to give a voice to a character who was in the shadows. Put the protagonist out of business.",
    mode: "online and offline",
    pocName1: "Shreya Prabhakar, Shreya Senapaty",
    pocNumber1: "95354 40123, 7675057722",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "23",
  },
  {
    title: "The Shape of me",
    description:
      "When art inspires poetry, it results in the geometrical juxtaposition of creative, chromatic expressions of our emotions. 'The Shape of me' encourages you to take inspiration from nature and write a reflective piece in its shape. Let nature give voice to your feelings, a shape to your poetry.",
    mode: "online and offline",
    pocName1: "Muskaan Kumar",
    pocNumber1: "9175922430",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "24",
  },
  {
    title: "Fraglore Valorant",
    description:
      'The most enthralling and awaited event "Fraglore" is backmore robust than ever this year. The beautiful chaos created by the abilities of our favorite agents, the age-old battle of terrorists and counter-terrorists, revolutionized soccer of rocket league, and our beloved battle royale; all are up this year for a scintillating sight that one ccan\'t miss. A versus of teams from all the colleges across the country, with a gaming prowress one dreams to possess, Fraglore shows no mercy for the slightest faltering in skillset.                                                                                                   The most anticipated tournament of the game that is on everyone’s lips right now. Teams of 5, each consisting of agents with unique abilities, face-off to earn the “Victory Tag”. Unique abilities, aiming skills, and intelligent strategies make the matches totally nail-biting.\xa0',
    mode: "online",
    pocName1: "Garvit Vyas",
    pocNumber1: "9686793032",
    pocName2: "Siddhant Jain",
    pocNumber2: "8839277867",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "25",
  },
  {
    title: "Fraglore CSGO",
    description:
      'The most enthralling and awaited event "Fraglore" is backmore robust than ever this year. The beautiful chaos created by the abilities of our favorite agents, the age-old battle of terrorists and counter-terrorists, revolutionized soccer of rocket league, and our beloved battle royale; all are up this year for a scintillating sight that one ccan\'t miss. A versus of teams from all the colleges across the country, with a gaming prowress one dreams to possess, Fraglore shows no mercy for the slightest faltering in skillset.                                                                                                   The “OG” game of the Search & Destroy series, where a team of terrorists and counter-terrorists. Battle each other, resembling real-life scenarios. Realistic and strategic gameplay, with team coordination, is what makes the game a “Battle of Wits”.',
    mode: "online",
    pocName1: "Prajwal Nayak",
    pocNumber1: "8792838739",
    pocName2: "Rudraksh Tiwari",
    pocNumber2: "7067705957",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "26",
  },
  {
    title: "Fraglore Rocket League",
    description:
      'The most enthralling and awaited event "Fraglore" is backmore robust than ever this year. The beautiful chaos created by the abilities of our favorite agents, the age-old battle of terrorists and counter-terrorists, revolutionized soccer of rocket league, and our beloved battle royale; all are up this year for a scintillating sight that one ccan\'t miss. A versus of teams from all the colleges across the country, with a gaming prowress one dreams to possess, Fraglore shows no mercy for the slightest faltering in skillset.                                                                                                 Fusion of “Road rage” and “Football”, teams demolish each other’s players with no fear of penalty or red cards. Aerial shots, pool shots, and extermination makes the match a spectacle to behold. Celebrations after jaw-breaking moments come second to no game, as you “Lofi” and “HiFi” to savor the moment with your team.',
    mode: "online",
    pocName1: "Teja Sai PV, ",
    pocNumber1: "8309246278",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "27",
  },
  {
    title: "Fraglore CODM/BGMI",
    description:
      '\nThe most enthralling and awaited event "Fraglore" is backmore robust than ever this year. The beautiful chaos created by the abilities of our favorite agents, the age-old battle of terrorists and counter-terrorists, revolutionized soccer of rocket league, and our beloved battle royale; all are up this year for a scintillating sight that one ccan\'t miss. A versus of teams from all the colleges across the country, with a gaming prowress one dreams to possess, Fraglore shows no mercy for the slightest faltering in skillset.\nCodm/Bgmi - The revolutionary game in the mobile industry, it offers the classic battle royale experience on mobile. Squads land on an island, search for weapons and use the environment guided by their survival instincts to be the last one standing. Locomotives or molotovs, grenades or flashbangs,\r\n\r\nMelee attacks and snipe shots, all resemble the real-life fighting scenarios. Do you have what it takes to get the “Chicken Dinner”?',
    mode: "online",
    pocName1: "Shyam N V",
    pocNumber1: "8604975791",
    pocName2: "Harsha",
    pocNumber2: "9440850268",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "28",
  },
  {
    title: "Glitterati",
    description:
      "A rampwalk event where participants use clothes to represent the theme of glitterati. The various participating teams are supposed to record a video in the clothes based on the theme while doing rampwalk. The video will be judged by the guest celebrity judges followed by a live QnA about their designs\r\n\r\n",
    mode: "online and offline",
    pocName1: "Devansh Mathukia",
    pocNumber1: "9869225827, 8169984251",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "29",
  },
  {
    title: "RAMPAGE",
    description:
      "Rampwalk for all members of GB; People can walk with their friends, wingies,  and by themselves as well.\r\n",
    mode: null,
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "30",
  },
  {
    title: "Fashion Panel",
    description: "Panel discussion on fashion by prominent personalities",
    mode: null,
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "31",
  },
  {
    title: "Alta costura",
    description:
      "This is an online competition having a single round.\nThe team members should record video individually from their respective places, and then these individual videos can be compiled to make a single entry.\nThe size of the team should be 8-20 with a minimum of 4 members present on the screen at once.\nThe video must be of 3-5 minutes of duration. Negative marking for exceeding the time limit.",
    mode: "online",
    pocName1: "Devansh Mathukia",
    pocNumber1: "9869225827, 8169984251",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "32",
  },
  {
    title: "Mr Ms Pearl",
    description:
      "A rampwalk event where participants use clothes to represent the theme of Glitterati",
    mode: "offline",
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "33",
  },
  {
    title: "Alfaaz",
    description:
      "From the quest for words ranging to the discovery of meanings, the epiphanies and realisations from various stimuli - we all tend to pen down a few words just like that, create anecdotes for our own selves or even to issue polemics.\n\nPresenting to all the platform of Alfaaz at Pearl, BPHC, to recite your Hindi-Urdu poetry treasures and experience the thrill of performing your self written pieces, in a language of your own.",
    mode: "online",
    pocName1: "Rudra Raj Awasthi",
    pocNumber1: "8009954169",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "34",
  },
  {
    title: "Youth Mahasabha",
    description:
      "Ideate. Create. Debate. (For those who hold in captive their opinions on current affairs and possess an ardent desire to let them all free, we present the Youth Mahasabha, a Hindi debate event at Pearl, BPHC, an opportunity for you to voice your trove of beliefs, compelling others to break open theirs.)",
    mode: "offline",
    pocName1: "Kartikay Dhall",
    pocNumber1: "9638930748",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "35",
  },
  {
    title:
      "Antakshari(this will be an offline event so no guarantee that this will be done)",
    description:
      "Knock knock!\nAre you the one who knows the lyrics to all the songs, or the one who vibes to all genres of music or the one who makes the best of playlists? Would you call yourself a music nerd?\nIf so, we've got some news! Presenting to you, Antakshari, but hatke.\nThe game we've all played but in a way we never have. \nJoin us to strike a feeling of nostalgia as we fight the new normal with melodies and lyrics.\nNo longer let the tune of a song stay stuck in your head. Sing it all out, right here.",
    mode: "offline",
    pocName1: "Riya Singh",
    pocNumber1: "8960709002",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "36",
  },
  {
    title: "Interview",
    description:
      "As it doesn't makes sense to call in famous celebrities as judges in online events we are planning to host an interview with a celebrity, the winners of alfaaz will be given a chance to perform in front of the guest",
    mode: "offline",
    pocName1: "Abhudaya Mishra",
    pocNumber1: "9953959223",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "37",
  },
  {
    title: "Kaleidoscope",
    description:
      "Catharsis Film Festival as a part of Pearl'22 proudly presents Kaleidoscope, It is one of the biggest Short Film competitions of the year. Your movie can be in any language, but it is compulsory to submit English subtitles along with the movie. ",
    mode: "online",
    pocName1: "Archis Sahu",
    pocNumber1: "7259028066",
    pocName2: null,
    pocNumber2: null,
    prize: 40000.0,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "38",
  },
  {
    title: "The Itinerary",
    description:
      "It is a Travel Film competition. Your vlog/film can be in any language, but it is advisable to submit English subtitles along with the vlog/film. \n\nThe vlog/film can be shot on any camera (Mobile or DSLR). They will be judged on the style and creativity and not on the quality of the footage.\n",
    mode: "offline/online and offline",
    pocName1: "Archis Sahu",
    pocNumber1: "7259028066",
    pocName2: null,
    pocNumber2: null,
    prize: 14000.0,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "39",
  },
  {
    title: "Football Manager",
    description:
      "An ascending-bid auction of the best footballers around the world, form the best teams possible with the funds available to you and compete with one another using FM simulations. ",
    mode: "offline",
    pocName1: "Gaurav Singh",
    pocNumber1: "9148399911",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "40",
  },
  {
    title: "Interrofiction",
    description:
      "step into the shoes of a fictional character and create conversations across fandoms with other participants",
    mode: "online and offline",
    pocName1: "Vidhi Mehta",
    pocNumber1: "9967514181",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "41",
  },
  {
    title: "Retrospective",
    description:
      'Come and participate in our flagship event - "Retrospective" which gives photographers all across India a chance to display their art. It is an online photography contest revolving around the following themes: 1)Neon/City lights 2)Photojournalism 3)Abstract photography 4)Long exposure 5)Astrophotography',
    mode: "online",
    pocName1: "Khushi Khanna",
    pocNumber1: "7428468181",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "42",
  },
  {
    title: "Expressions",
    description:
      "A race to capture the best candid photos, the perfect opportunity to show your skills as you move around the fest camera in hand capturing the most stripped down moments of the fest in the form of candids.",
    mode: "offline",
    pocName1: "Khushi Khanna",
    pocNumber1: "7428468181",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "43",
  },
  {
    title: "Midnight AV Quiz",
    description:
      "Are you a fiend for the night?\n\nNo one attends events in the pique summer daylight, that's why we're having one at this comforting hour. \n\nKing Solomon is asleep and you'll be on your own, come test your wit against Audio and Visual questions that span the entire human knowledge. \n\nWe'll see you right after the inauguration, as the clock strikes the hour. \nDon't fall asleep in the Auditorium and bring your own pens.",
    mode: "offline",
    pocName1: "Abhay Jagannath",
    pocNumber1: "8790500333",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "44",
  },
  {
    title: "Sci-Tech Quiz",
    description:
      "If eccentricities of scientific geniuses and bizarre bleeding edge technologies intrigue you, then the Orbe Novo Sci-Tech quiz is the place to be. Hosted by Major Chandrakant Nair, this event promises to keep your neurons and keyboards firing alike(Googling would be a wasted effort here though, don’t bother). From the wheel to Whatsapp and more, a question could come from anywhere in the space-time continuum. Only one thing is a given - you will be puzzled, confused, and excited. Clear your calendars, the event is on 3rd April!",
    mode: "online",
    pocName1: "Abhay Jagannath",
    pocNumber1: "8790500333",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "45",
  },
  {
    title: "Bizzinga - A Buisness & Entrepreneurs Quiz",
    description:
      "Did you know that Walmart makes $1.8 million in profits every hour? And every week nearly one-third of the US population visits Walmart. Do these facts fascinate you? Do you love watching Shark Tank and find yourself keeping up with new developments in the business world? If your answer to any of these questions is yes then Bizzinga is the perfect opportunity for you to test your knowledge amongst your fellow business nerds. Get ready to take a deep dive into the world of Businesses, Start ups and more and expand your knowledge in this ever-expanding field.",
    mode: "offline",
    pocName1: "Abhay Jagannath",
    pocNumber1: "8790500333",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "46",
  },
  {
    title: "Open General Quiz",
    description:
      "The beauty of quizzing comes when everyone gives their 110%. The Open quiz, hosted by Major Chandrakant Nair, is slated to be a mind-boggling experience, which will satisfy the trivia requirements you have had ever since Covid hit. We are inviting everyone to come and compete. The world of Quizzing is all about opening new doors and exploring new worlds, and this is the perfect opportunity at Orbe Novo 2022. Give everything you have, and leave the rest to the quizmaster!",
    mode: "online",
    pocName1: "Vaibhav Jha",
    pocNumber1: "72178 34030",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "47",
  },
  {
    title: "Shifting Paradigms - A Cultural Quiz",
    description:
      "Do you like exploring the unknown? Along that track, you might have come across illusions in the past. What’s mysterious about them is that you never know whether its a mirage or a reality, a hallucination or an actuality. What awaits you ahead continues to remain uncertain until the end.\nThat’s what makes illusions fascinating.\nWell, based on this theme, we have a quiz lined up for you. Get ready to alter your way of thinking to crack the question, or you may lose yourself in the enigma.\nOn this note, the Quiz Club of BITS Pilani Hyderabad Campus proudly presents ‘Shifting Paradigms,’ a cultural quiz for Orbe Novo. Get ready to give your inner explorer and quizzer a wake-up call as you rise to the quest and battle it out with your friends in an engaging quiz based on questions that will make you go ahhhh !",
    mode: "offline",
    pocName1: "Vaibhav Jha",
    pocNumber1: "72178 34030",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "48",
  },
  {
    title: "Rang Answers Only - A Quiz on Colours",
    description:
      "Are you looking to take part in a quiz, like never before? Rang Answers Only - A Quiz on Colours, hosted by Jalaj Maheshwari is probably the color you need in life. The Quiz will happen on the 2nd of April. Join us on this ride, for a fun quiz that challenges not only your wit but your affinity for hue.",
    mode: "online",
    pocName1: "Vaibhav Jha",
    pocNumber1: "72178 34030",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "49",
  },
  {
    title: "Around The World In 80 Minutes",
    description:
      "Get ready for an adventure, as the Sanskrit and Foreign Language Club brings to you an event like no other. In Around the World in 80 Minutes, you get to experience an immersive RPG environment brought to life. Dropped into a foreign country, you are armed with only your wit and charm as you navigate the scene around you, interacting with characters that may help (or harm!) you along your journey. As you move from one country to the other, be prepared to be met with a burst of colour, flair and a whole host of intriguing personas, each crazier than the last.",
    mode: "offline",
    pocName1: "Ankita Behera",
    pocNumber1: "8280292201",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "50",
  },
  {
    title: "Renegade",
    description:
      "Behind mirages, smokescreens and veils of mystery, SaFL presents a brand-new, enigma of an event: Renegade. As you deal with lurking presences and conspicuous shadows, this event is sure to keep you on your toes.\nAs illusion and reality blend together, you’ll be second-guessing your own vision within no time.\nBe on guard, and remember, above all else: nothing it as it seems.",
    mode: "online",
    pocName1: "Sanshrey Keshri",
    pocNumber1: "7331170345",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "51",
  },
  {
    title: "Anime Quiz",
    description:
      "Are you lonely? \nDo you spend the better half of a day dreaming of a beautiful SO, preferably from a country in the Far East, your imagination only broken by a sudden urge to watch the new Devil Killer™ episode?\nIf you’re the type of person who has zero social skills and even fewer friends, then SaFL has the perfect event for you: our big, beefy, and well-endowed Anime Quiz, back and better than ever.\n\null extravaganza bonullza welcoming all NEETs, shut-ins and miscellaneous weebs.",
    mode: null,
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "52",
  },
  {
    title: "Masterstroke",
    description:
      "Masterstroke is the Art competition of Pearl, BPHC.\xa0\nIt has 2 major categories, b/w, and color. Submissions may be based on any medium like acrylic, oils, pastels, or watercolor, and even digital and will consist of only one round.\nAll the submissions are judged based on the quality, creativity, and perfection in the execution of their ideas.",
    mode: "online and offline/online",
    pocName1: "Nirmalya Ghosh",
    pocNumber1: "8179749977",
    pocName2: "Aayush Tiwari",
    pocNumber2: "9880523444",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "53",
  },
  {
    title: "Exhibition",
    description:
      "Members of the Club will showcase all their artworks in a classroom; if we are given access;",
    mode: "offline",
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "54",
  },
  {
    title: "Pictionary",
    description:
      "Ever thought that guessing your friend's drawing could fetch you money? Well shades considers that guessing is an art too. We bring forward to you the perfect event that is fun-filled, artistic and that would totally get your adrenaline rushing. It's a game that matters! ",
    mode: "offline",
    pocName1: "Nirmalya Ghosh",
    pocNumber1: "8179749977",
    pocName2: "Aayush Tiwari",
    pocNumber2: "9880523444",
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "55",
  },
  {
    title: "Cinematic Trailer Making",
    description:
      "Trailers are fundamental tools to entice audiences into an enigmatic fictional world. This Pearl, VFx Club, BITS Pilani Hyderabad Campus invites you to create a lucid, enthralling trailer to draw your viewers into your favorite fantasy. You can choose to make it about your favorite movie, tv show, anime, and even characters. Use this opportunity to express yourself and test your creativity and imagination.",
    mode: "online and offline",
    pocName1: "Sailesh Duddupudi",
    pocNumber1: "8124191868",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "56",
  },
  {
    title: "Ad Mad",
    description:
      "Have you ever felt thirsty after looking at a soda commercial? Ever thought about the effort that goes into the videography and creation of that commercial? Here’s an opportunity to make an advertisement of your favorite product be it phone, a car or even a pen! Test your creativity by marketing your favorite product.\xa0",
    mode: "online and offline",
    pocName1: "Sailesh Duddupudi",
    pocNumber1: "8124191868",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "57",
  },
  {
    title: "Shred Wars",
    description:
      "Contestants will be given a chance to show off their raw, solo performing talent by composing their own solos over a backing track.There will be a large cash prizes and winning entries will be feautured on the fest's official social media pages.Looking forwrad to the entries!",
    mode: "online",
    pocName1: "Varun Vaddiraju",
    pocNumber1: "8367012937",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "58",
  },
  {
    title: "A capella",
    description:
      "Participants have to choose a song of their choice and cover it in a cappella. No backing track/ karaoke is allowed. Clapping, finger snapping alongside humming along/ singing harmonies is allowed. Each entry is to be around 1-2mins",
    mode: "online",
    pocName1: "Dhruv Gopal",
    pocNumber1: "9620201692",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "59",
  },
  {
    title: "Chords From a Hat",
    description:
      "Participants will choose one theme out of a pool of predetermined themes. Each theme will be accompanied by a standard chord progression that will convey the emotion of the theme. Each contestant will have to submit an original composition of around 2 minutes length.",
    mode: null,
    pocName1: null,
    pocNumber1: null,
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "60",
  },
  {
    title: "Pardon My French",
    description:
      "Participants guess the song from lyrics run through google translate",
    mode: "offline",
    pocName1: "Samarpith Rout",
    pocNumber1: "8971702411",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "61",
  },
  {
    title: "Fuse It",
    description: "Participants create Indo-Western fusion mashups",
    mode: "offline",
    pocName1: "Anullya Pinapati",
    pocNumber1: "8367012937",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "62",
  },
  {
    title: "Masterclass on Music",
    description: "Prominent artist conducting masterclass",
    mode: "online",
    pocName1: "Antara Arvind",
    pocNumber1: "7358317077",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: true,
    id: "63",
  },
  {
    title: "Gandhaara - Vocal",
    description:
      "Solo Indian Classical Vocal Competition\n\nMusic is a universal language, a means that can surpass the barriers of language and borders. Indian classical music, through its melody, rhythm, and poetic expressions holds the power to reach out to people, in ways that are unimaginable. Swaranjali, the classical dance and music club of BITS Pilani Hyderabad brings to you Gandhaara, the Indian classical music competition (Vocal). The competition will give a chance to the participants to showcase their talent and creativity as you immerse yourself in a world of raagas and taalas and go on a journey through various emotions.\n\nFor this event we are delighted to host Vid. Sikkil Gurucharan as the judge for the event.",
    mode: "online",
    pocName1: "Ramakrishna",
    pocNumber1: "8310670231",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "64",
  },
  {
    title: "Gandhaara - Musical Concert",
    description:
      "Group Indian Classical Concert Competition:\n\nMusic is a universal language, a means that can surpass the barriers of language and borders. Indian classical music, through its melody, rhythm, and poetic expressions holds the power to reach out to people, in ways that are unimaginable.Swaranjali, the classical dance and music club of BITS Pilani Hyderabad brings to you Gandhaara, the Indian classical music concert competition . The competition will give a chance to the participants to showcase their talent and creativity as you immerse yourself in a world of raags and taals and go on a journey through various emotions.",
    mode: "online",
    pocName1: "Ethiraja Balaji",
    pocNumber1: "9032055775",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "65",
  },
  {
    title: "Aakara (Dance competition)",
    description:
      "India is a country of diversity and rich culture.The eight classical dances forms of India beautifully depict the culture and cultural diversity of our country. From the footwork to the mudras and the expressions,it all blends together to put forth a graceful performance\xa0by dedicated performers. Swaranjali, the classical dance and music club of BITS Pilani Hyderabad Campusbrings to you Aakara, the Indian classical dance competition.",
    mode: "online",
    pocName1: "Samyu Kamtam",
    pocNumber1: "8008004472",
    pocName2: null,
    pocNumber2: null,
    prize: null,
    poster:
      "https://firebasestorage.googleapis.com/v0/b/orbenovo-22.appspot.com/o/Atmos.png?alt=media&token=52237b99-9313-47d5-9705-6fd9d12b0c46",
    link: "www.google.com",
    isWorkshop: false,
    id: "66",
  },
];
